### PR TITLE
feat: add support for Mac darwin

### PR DESCRIPTION
**Pull request by georgebutter**
So I ran the lint command and it has made this PR rather messy and touched a lot of lines that aren't really pertinent to this PR.

I am happy to remove them, but as this is actually based on what the eslint config is set to, so I wasn't sure.

Could try and split them in to separate PRs if you would like both of them without the messiness.

### CODE REVIEW

**Comment by georgebutter** [comment]
Resolves #2

**Comment by DecDuck** [comment]
Looks good! The mess shouldn't be too much of a problem. I'm going to wait for the maintainer (@nmattela) to merge this - I don't want to break anything.

**Comment by georgebutter** [comment]
Raised #4 which can be safely merged first to clear up the actual changes in this PR

**Review by nmattela — APPROVED** [review]
LGTM, thanks for your contribution!

It will take some time before this update hits the extension marketplace as I will need to update the current version manually. I'll make work of that right now!

**Pull request merged**
